config/routes.rb
Rails.application.routes.draw do


  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  # 会員側のルーティング設定
  root to: 'public/homes#top'
  get 'public/homes/about' => 'public/homes#about', as:'about'

  namespace :public do
    resources :items, only: [:index, :show ,:create]
    # resources :registrations, only: [:create, :new]
    # resources :sessions, only: [:new, :create, :destroy]
    resource :customer, only: [:show, :edit, :update]
    resources :cart_items, only: [:index, :update, :destroy, :create] do
        collection do
           delete 'destroy_all'
        end
    end

    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'
    get 'customers/check' => 'customers#check'
    patch 'withdrawl' => 'customers#withdrawl'


    resources :orders, only: [:new, :create, :index, :show] do

    end
    resources :order_details, only: []
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
  # 管理者側のルーティング設定
  get 'admin/homes/top' => 'admin/homes#top', as:'top'

  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :homes, only: [:top]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    # resources :sessions, only: [:new, :create, :destroy]
  end


end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer


def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

belongs_to :item
belongs_to :customer




def subtotal
    item.add_tax_price * amount
end



end

app/models/customer.rb
class Customer < ApplicationRecord

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :addresses, dependent: :destroy
 has_many :cart_items, dependent: :destroy
 has_many :orders, dependent: :destroy

# enum is_active: { member: 0, withdrawal: 1 }

  def full_name
    last_name+first_name
  end

  def full_name_kana
    last_name_kana+first_name_kana
  end

  def own_infomation
    postal_code+address+full_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  # enum is_active: { sale: 0, discontinued: 1 }


def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
end


def add_tax_price
  (self.price * 1.1).round
end

end

app/models/order.rb
class Order < ApplicationRecord

 enum payment_method: { credit_card: 0, transfer: 1 }
 enum status: { waiting: 0, deposited: 1, production: 2, preparation: 3, sent: 4 }

 has_many :order_details, dependent: :destroy
 belongs_to :customer

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item
    enum making_status: {impossible: 0, waiting: 1, start: 2, finish:3 }


    def subtotal
    item.add_tax_price * amount
    end

    def add_tax_price
     (self.price * 1.1).round
    end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

def index
  @customers = Customer.page(params[:page]).per(10)
end

def show
  @customer = Customer.find(params[:id])
end

def edit
  @customer = Customer.find(params[:id])
end

def update
  @customer = Customer.find(params[:id])
  @customer.update(customer_params)
  redirect_to admin_customer_path
end

private

def customer_params
  params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_active)
end




end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

def index
  @genre = Genre.new
  @genres = Genre.all
end

def new
  @genre = Genre.new
end

def create
  @genre = Genre.new(genre_params)
  @genre.save
  redirect_to admin_genres_path
end

def edit
  @genre = Genre.find(params[:id])

end

def update
  @genre = Genre.find(params[:id])
  @genre.update(genre_params)
  redirect_to admin_genres_path

end

private
  def genre_params
    params.require(:genre).permit(:name)
  end


end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

def top
  @orders = Order.page(params[:page]).per(10)
end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

def new
  @item = Item.new
end

def create
  @item = Item.new(item_params)
  @item.save
  redirect_to admin_item_path(@item.id)
end

def index
  @items = Item.page(params[:page]).per(10)
end


def show
  @item = Item.find(params[:id])
end

def edit
  @item = Item.find(params[:id])
end

def update
  @item = Item.find(params[:id])
  @item.update(item_params)
  redirect_to admin_item_path(@item.id)
end

private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

def show
  @order = Order.find(params[:id])
  @order_details = @order.order_details
  @total = @order.order_details.inject(0) { |sum, order_detail| sum + order_detail.item.add_tax_price * order_detail.amount }
end

def update
  @order = Order.find(params[:id])
  @order.update(status: params[:order][:status])
  redirect_to admin_order_path(@order.id)

end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<h4><%= @customer.full_name %>さんの会員情報編集</h4>

<%= form_with model: @customer, url:admin_customer_path do |f| %>
<table class="table">
  <tbody>

 <tr>
   <th>会員ID</th>
   <th><%= @customer.id %></th>
 </tr>

 <tr>
   <th>氏名</th>
   <th>
     <%= f.text_field :last_name %>
     <%= f.text_field :first_name %>
   </th>
 </tr>

 <tr>
   <th>フリガナ</th>
   <th>
     <%= f.text_field :last_name_kana %>
     <%= f.text_field :first_name_kana %>
   </th>
 </tr>

 <tr>
   <th>郵便番号</th>
   <th><%= f.text_field :postal_code %></th>
 </tr>


 <tr>
   <th>住所</th>
   <th><%= f.text_area :address %></th>
 </tr>

 <tr>
   <th>電話番号</th>
   <th><%= f.text_field :telephone_number %></th>
 </tr>


 <tr>
   <th>メールアドレス</th>
   <th><%= f.email_field :email %></th>
 </tr>

 <tr>
   <th>会員ステータス</th>
   <th>
     <%= f.radio_button :is_active, true %>
     <%= f.label :is_active, "有効" %>

     <%= f.radio_button :is_active, false %>
     <%= f.label :is_active, "退会" %>
   </th>
 </tr>


</tbody>
</table>

<%= f.submit "編集内容を保存", class:"btn btn-success" %>

<% end %>

app/views/admin/customers/index.html.erb
<h4>会員一覧</h4>

<table class="table">
<thead class="thead-dark">
 <tr>

  <th scope="col">会員ID</th>
  <th scope="col">氏名</th>
  <th scope="col">メールアドレス</th>
  <th scope="col">ステータス</th>

 </tr>
</thead>

<tbody>
<!--この辺一応、modelでカラム名を確認する。-->
<% @customers.each do |customer| %>
 <tr>
  <td><%= customer.id %></td>
  <td><%= link_to customer.full_name , admin_customer_path(customer) %></td>
  <td><%= customer.email %></td>
  <td>
    <% if customer.is_active %>
    有効
    <% else %>
    退会
    <% end %>
    </td>
</tr>
<% end %>

</tbody>
</table>

<%= paginate @customers %>

app/views/admin/customers/show.html.erb
<h4><%= @customer.full_name %>さんの会員詳細</h4>

<table class="table">
  <tbody>

    <tr>
      <th>会員ID</th>
      <th><%= @customer.id %></th>
    </tr>


    <tr>
      <th>氏名</th>
      <th><%= @customer.full_name %></th>
    </tr>


    <tr>
      <th>フリガナ</th>
      <th><%= @customer.full_name_kana %></th>
    </tr>


    <tr>
      <th>郵便番号</th>
      <th><%= @customer.postal_code %></th>
    </tr>


    <tr>
      <th>住所</th>
      <th><%= @customer.address %></th>
    </tr>

    <tr>
      <th>電話番号</th>
      <th><%= @customer.telephone_number %></th>
    </tr>

    <tr>
      <th>メールアドレス</th>
      <th><%= @customer.email %></th>
    </tr>


    <tr>
      <th>会員ステータス</th>
      <th>
        <% if @customer.is_active %>
        有効
        <% else %>
        退会
        <% end %>
      </th>
    </tr>


 </tbody>
</table>

<div class="text-center">
<%= link_to "編集する", edit_admin_customer_path, class:"btn btn-success" %>
<%= link_to "注文履歴一覧を見る", public_orders_path, class:"btn btn-primary" %>
</div>