config/routes.rb
Rails.application.routes.draw do


  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  # 会員側のルーティング設定
  root to: 'public/homes#top'
  get 'public/homes/about' => 'public/homes#about', as:'about'

  namespace :public do
    resources :items, only: [:index, :show ,:create]
    # resources :registrations, only: [:create, :new]
    # resources :sessions, only: [:new, :create, :destroy]
    resource :customer, only: [:show, :edit, :update]
    resources :cart_items, only: [:index, :update, :destroy, :create] do
        collection do
           delete 'destroy_all'
        end
    end

    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'
    get 'customers/check' => 'customers#check'
    patch 'withdrawl' => 'customers#withdrawl'


    resources :orders, only: [:new, :create, :index, :show] do

    end
    resources :order_details, only: []
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
  # 管理者側のルーティング設定
  get 'admin/homes/top' => 'admin/homes#top', as:'top'

  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :homes, only: [:top]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    # resources :sessions, only: [:new, :create, :destroy]
  end


end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer


def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

belongs_to :item
belongs_to :customer




def subtotal
    item.add_tax_price * amount
end



end

app/models/customer.rb
class Customer < ApplicationRecord

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :addresses, dependent: :destroy
 has_many :cart_items, dependent: :destroy
 has_many :orders, dependent: :destroy

# enum is_active: { member: 0, withdrawal: 1 }

  def full_name
    last_name+first_name
  end

  def full_name_kana
    last_name_kana+first_name_kana
  end

  def own_infomation
    postal_code+address+full_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  # enum is_active: { sale: 0, discontinued: 1 }


def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
end


def add_tax_price
  (self.price * 1.1).round
end

end

app/models/order.rb
class Order < ApplicationRecord

 enum payment_method: { credit_card: 0, transfer: 1 }
 enum status: { waiting: 0, deposited: 1, production: 2, preparation: 3, sent: 4 }

 has_many :order_details, dependent: :destroy
 belongs_to :customer

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item
    enum making_status: {impossible: 0, waiting: 1, start: 2, finish:3 }


    def subtotal
    item.add_tax_price * amount
    end

    def add_tax_price
     (self.price * 1.1).round
    end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

def index
  @genre = Genre.new
  @genres = Genre.all
end

def new
  @genre = Genre.new
end

def create
  @genre = Genre.new(genre_params)
  @genre.save
  redirect_to admin_genres_path
end

def edit
  @genre = Genre.find(params[:id])

end

def update
  @genre = Genre.find(params[:id])
  @genre.update(genre_params)
  redirect_to admin_genres_path

end

private
  def genre_params
    params.require(:genre).permit(:name)
  end


end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

def top
  @orders = Order.page(params[:page]).per(10)
end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

def new
  @item = Item.new
end

def create
  @item = Item.new(item_params)
  @item.save
  redirect_to admin_item_path(@item.id)
end

def index
  @items = Item.page(params[:page]).per(10)
end


def show
  @item = Item.find(params[:id])
end

def edit
  @item = Item.find(params[:id])
end

def update
  @item = Item.find(params[:id])
  @item.update(item_params)
  redirect_to admin_item_path(@item.id)
end

private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

def show
  @order = Order.find(params[:id])
  @order_details = @order.order_details
  @total = @order.order_details.inject(0) { |sum, order_detail| sum + order_detail.item.add_tax_price * order_detail.amount }
end

def update
  @order = Order.find(params[:id])
  @order.update(status: params[:order][:status])
  redirect_to admin_order_path(@order.id)

end



end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<h4>ジャンル編集</h4>

<%= form_with model: @genre, url:admin_genre_path(@genre.id), method: :patch do |f| %>

<p>ジャンル名</p>
<%= f.text_area :name %>

<%= f.submit '変更を保存', class:"btn btn-success" %>

<% end %>

app/views/admin/genres/index.html.erb
<h4>ジャンル一覧・追加</h4>

<%= form_with model: @genre, url: admin_genres_path do |f| %>

<p>ジャンル名</p>

<%= f.text_field :name %>

<%= f.submit '新規登録', class:"btn btn-success" %>

<% end %>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">ジャンル</th>
      <th scope="col"></th>
    </tr>
  </thead>
 <tbody>
  <% @genres.each do |genre| %>
  <tr>
    <td><%= genre.name %></td>
    <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class:"btn btn-success" %></td>
  </tr>
  <% end %>
 </tbody>
</table>

app/views/admin/items/edit.html.erb
<h4>商品編集</h4>
<div class="text-center">
<%= form_with model: @item, url: admin_item_path do |f| %>

<table class="table">
<tbody>
  <tr>
  <th>商品画像</th>
  <th><%= f.file_field :image, accept: "image/*" %></th>
  </tr>
  <tr>

  <tr>
    <th>商品名</th>
    <th><%= f.text_field :name %></th>
  </tr>

  <tr>
    <th>商品説明</th>
    <th><%= f.text_area :introduction %></th>
  </tr>

  <tr>
    <th>ジャンル</th>
    <th><%= f.collection_select :genre_id, Genre.all, :id, :name, { prompt:"-- 選択してください --"} %></th>
  </tr>

  <tr>
    <th>税抜価格</th>
    <th><%= f.number_field :price %>円
       <div class="error">整数のみ入力できます</div>
    </th>

  </tr>

  <tr>
    <th>販売ステータス</th>
    <th><%= f.radio_button :is_active, true %>
        <%= f.label :is_active, "販売中" %>

        <%= f.radio_button :is_active, false %>
        <%= f.label :is_active, "販売停止中" %>
     </th>
  </tr>


</tbody>
</table>

<%= f.submit '変更を保存', class:"btn btn-success" %>

<% end %>
</div>

app/views/admin/items/index.html.erb
<h4>商品一覧</h4>
<%= link_to "新規登録", new_admin_item_path, class:"btn btn-success" %>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">商品ID</th>
      <th scope="col">商品名</th>
      <th scope="col">税抜価格</th>
      <th scope="col">ジャンル</th>
      <th scope="col">ステータス</th>
    </tr>
  </thead>
<tbody>
<% @items.each do |item| %>
<tr>
  <td><%= item.id %></td>
  <td><%= link_to item.name, admin_item_path(item.id) %></td>
  <td><%= item.price.to_s(:delimited) %></td>
  <td><%= item.genre.name %></td>
  <td>
    <% if item.is_active %>
    販売中
    <% else %>
    販売停止中
    <% end %>
  </td>
</tr>


<% end %>
</tbody>
</table>
<%= paginate @items %>

app/views/admin/items/new.html.erb
<h4>新規商品登録</h4>
<div class="text-center">
<%= form_with model: @item, url: admin_items_path do |f| %>

<table class="table">
<tbody>
  <tr>
  <th>商品画像</th>
  <th><%= f.file_field :image, accept: "image/*" %></th>
  </tr>
  <tr>
    <th>商品名</th>
    <th><%= f.text_field :name %></th>
  </tr>

  <tr>
    <th>商品説明</th>
    <th><%= f.text_area :introduction %></th>
  </tr>

  <tr>
    <th>ジャンル</th>
    <th><%= f.collection_select :genre_id, Genre.all, :id, :name, { prompt:"-- 選択してください --"} %></th>
  </tr>

  <tr>
    <th>税抜価格</th>
    <th><%= f.number_field :price %>円
       <div class="error">整数のみ入力できます</div>
    </th>

  </tr>

  <tr>
    <th>販売ステータス</th>
    <th><%= f.radio_button :is_active, true %>
        <%= f.label :is_active, "販売中" %>

        <%= f.radio_button :is_active, false %>
        <%= f.label :is_active, "販売停止中" %>
     </th>
  </tr>

</tbody>
</table>

<%= f.submit '新規登録', class:"btn btn-success" %>

<% end %>

</div>

app/views/admin/items/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<div class="row">


<h4>商品詳細</h4>

<div class="col-md-4">
<p><%= image_tag @item.get_image(200, 200) %></p>
</div>

<div class="col-md-8">
<table class="table">
<tbody>
    <tr>
        <th>商品名</th>
        <th><%= @item.name %></th>
    </tr>

    <tr>
        <th>商品説明</th>
        <th><%= @item.introduction %></th>
    </tr>

    <tr>
        <th>ジャンル</th>
        <th><%= @item.genre.name %></th>
    </tr>

    <tr>
        <th>税込価格（税抜価格）</th>
        <th><%= @item.add_tax_price.to_s(:delimited) %>(<%= @item.price.to_s(:delimited) %>)円</th>
    </tr>

    <tr>
        <th>販売ステータス</th>
        <th>
            <% if @item.is_active %>
            販売中
            <% else %>
            販売停止中
            <% end %>
        </th>
    </tr>

</tbody>
</table>
<%= link_to "編集する", edit_admin_item_path, class:"btn btn-success" %>
</div>
</div>
</div>

app/views/admin/orders/show.html.erb
<h4>注文履歴詳細</h4>

<table class="table">
  <tbody>
  <tr>
  <th>購入者</th>
  <th><%= @order.customer.full_name %></th>
  </tr>

  <tr>
  <th>注文日</th>
  <th><%= l @order.created_at %></th>
  </tr>

  <tr>
  <th>配送先</th>
  <th>
    <%= @order.postal_code %>
    <%= @order.address %></br>
    <%= @order.name %>
  </th>
  </tr>

  <tr>
  <th>支払方法</th>
  <th><%= @order.payment_method_i18n %></th>
  </tr>

  <tr>
  <th>注文ステータス</th>
  <th><%= form_with model: @order, url:admin_order_path, method: :patch do |f| %>
      <%= f.select :status, Order.statuses_i18n.invert %>
      <%= f.submit "更新", class:"btn btn-success" %>
      <% end %>
  </th>
  </tr>

</tbody>
</table

<div="container">
<div class="row">

<div class="col">
<table class="table">
  <thead class="thead-dark">

  <tr>
    <th scope="col">商品名</th>
    <th scope="col">単価（税込）</th>
    <th scope="col">数量</th>
    <th scope="col">小計</th>
    <th scope="col">制作ステータス</th>
    <th scope="col"></th>
  </tr>
  </thead>

  <tbody>
    <% @order_details.each do |order_detail| %>
    <tr>
      <td><%= order_detail.item.name %></td>
      <td><%= order_detail.add_tax_price %></td>
      <td><%= order_detail.amount %></td>
      <td><%= order_detail.subtotal.to_s(:delimited) %></td>

      <td>
      <%= form_with model: order_detail, url:admin_order_detail_path(order_detail.id), method: :patch do |f| %>
      <%= f.select :making_status, OrderDetail.making_statuses_i18n.invert %>
      <%= f.submit "更新", class:"btn btn-success" %>
      <% end %>
     </td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

  <div class="col">
  <table class="table table-bordered">
    <tbody>
      <tr>
        <th>商品合計</th>
        <th><%= @total.round.to_s(:delimited) %></th>
      </tr>
      <tr>
        <th>送料</th>
        <th><%= 800 %></th>
      </tr>
      <tr>
        <th>請求金額合計</th>
        <th><%= @order.billing_amount.to_s(:delimited) %></th>
      </tr>
    </tbody>

  </table>
  </div>

  </div>
  </div>