config/routes.rb
Rails.application.routes.draw do


  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  # 会員側のルーティング設定
  root to: 'public/homes#top'
  get 'public/homes/about' => 'public/homes#about', as:'about'

  namespace :public do
    resources :items, only: [:index, :show ,:create]
    # resources :registrations, only: [:create, :new]
    # resources :sessions, only: [:new, :create, :destroy]
    resource :customer, only: [:show, :edit, :update]
    resources :cart_items, only: [:index, :update, :destroy, :create] do
        collection do
           delete 'destroy_all'
        end
    end

    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'
    get 'customers/check' => 'customers#check'
    patch 'withdrawl' => 'customers#withdrawl'


    resources :orders, only: [:new, :create, :index, :show] do

    end
    resources :order_details, only: []
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
  # 管理者側のルーティング設定
  get 'admin/homes/top' => 'admin/homes#top', as:'top'

  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :homes, only: [:top]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    # resources :sessions, only: [:new, :create, :destroy]
  end


end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer


def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

belongs_to :item
belongs_to :customer




def subtotal
    item.add_tax_price * amount
end



end

app/models/customer.rb
class Customer < ApplicationRecord

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :addresses, dependent: :destroy
 has_many :cart_items, dependent: :destroy
 has_many :orders, dependent: :destroy

# enum is_active: { member: 0, withdrawal: 1 }

  def full_name
    last_name+first_name
  end

  def full_name_kana
    last_name_kana+first_name_kana
  end

  def own_infomation
    postal_code+address+full_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  # enum is_active: { sale: 0, discontinued: 1 }


def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
end


def add_tax_price
  (self.price * 1.1).round
end

end

app/models/order.rb
class Order < ApplicationRecord

 enum payment_method: { credit_card: 0, transfer: 1 }
 enum status: { waiting: 0, deposited: 1, production: 2, preparation: 3, sent: 4 }

 has_many :order_details, dependent: :destroy
 belongs_to :customer

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item
    enum making_status: {impossible: 0, waiting: 1, start: 2, finish:3 }


    def subtotal
    item.add_tax_price * amount
    end

    def add_tax_price
     (self.price * 1.1).round
    end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

def top
  @orders = Order.page(params[:page]).per(10)
end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

def new
  @item = Item.new
end

def create
  @item = Item.new(item_params)
  @item.save
  redirect_to admin_item_path(@item.id)
end

def index
  @items = Item.page(params[:page]).per(10)
end


def show
  @item = Item.find(params[:id])
end

def edit
  @item = Item.find(params[:id])
end

def update
  @item = Item.find(params[:id])
  @item.update(item_params)
  redirect_to admin_item_path(@item.id)
end

private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <!--管理者がログインをした場合はどうしたら？-->
      <!--管理者-->
      <% if admin_signed_in? %>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
         <a class ="navbar-brand">ながのCAKE</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>

            <a class="nav-link"><%= link_to "商品一覧", admin_items_path %></a>
            <a class="nav-link"><%= link_to "会員一覧", admin_customers_path %></a>
            <a class="nav-link"><%= link_to "注文履歴一覧", top_path %></a>
            <a class="nav-link"><%= link_to "ジャンル一覧", admin_genres_path %></a>
            <a class="nav-link"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete %></a>
        </div>
      </nav>
      <!--customers-->
      <% elsif customer_signed_in? %>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
         <a class ="navbar-brand">ながのCAKE</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>

           <a class="nav-link"><%= link_to "マイページ", public_customer_path %></a>
           <a class="nav-link"><%= link_to "商品一覧", public_items_path %></a>
           <a class="nav-link"><%= link_to "カート", public_cart_items_path %></a>
           <a class="nav-link"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete %></a>
         </div>
      </nav>
      <!--それ以外-->
      <% else %>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
         <a class ="navbar-brand">ながのCAKE</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <a class="nav-link"><%= link_to "About", about_path %></a>
          <a class="nav-link"><%= link_to "商品一覧", public_items_path %></a>
          <a class="nav-link"><%= link_to "新規登録", new_customer_registration_path %></a>
          <a class="nav-link"><%= link_to "ログイン", new_customer_session_path %></a>
        </div>
      </nav>

      <% end %>


    </header>
    <%= yield %>

　　　<footer class="footer">
  　　　<div class="container">
    　<p class="text-muted">NAGANO CAKE.</p>
  　　</div>
　　　</footer>
  </body>
</html>